name: Build

on:
  workflow_dispatch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Build solution
        run: dotnet build Osiris.sln

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Automated release created by Github Actions and ChatGPT
          draft: false
          prerelease: false
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: Osiris.sln
